export const COLLECTIONS = {
  users: "users",
  workspaces: "workspaces",
  workspaceMembers: "workspace_members",
  sessions: "sessions",
  paymentLinks: "payment_links",
  transactions: "transactions",
  balances: "balances",
  activityEvents: "activity_events",
  activityEventsArchive: "activity_events_archive",
  invoices: "invoices",
  workspaceDailyStats: "workspace_daily_stats",
  apiKeys: "api_keys",
  agents: "agents",
  securityAudit: "security_audit",
  dbMeta: "db_meta",
} as const;
