export const COLLECTIONS = {
  users: "users",
  workspaces: "workspaces",
  workspaceMembers: "workspace_members",
  sessions: "sessions",
  paymentLinks: "payment_links",
  transactions: "transactions",
  balances: "balances",
  activityEvents: "activity_events",
  activityEventsArchive: "activity_events_archive",
  invoices: "invoices",
  workspaceDailyStats: "workspace_daily_stats",
  apiKeys: "api_keys",
  agents: "agents",
  securityAudit: "security_audit",
  dbMeta: "db_meta",
  agentPolicies: "agent_policies",
  policyDecisions: "policy_decisions",
  agentSpendDaily: "agent_spend_daily",
  agentSpendMonthly: "agent_spend_monthly",
  paymentApprovals: "payment_approvals",
  idempotencyKeys: "idempotency_keys",
  webhookEndpoints: "webhook_endpoints",
  webhookDeliveries: "webhook_deliveries",
} as const;
